/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main.librarian;

import javax.swing.table.DefaultTableModel;
import swing.UIController;
import view.login.LoginFrame;

/**
 *
 * @author Admin
 */
public class LibrarianMainFrame extends javax.swing.JFrame {
  
    /**
     * Creates new form LibrarianMainFrame
     */
    public LibrarianMainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel_Borrow.setBackground(jPanel_Title.getBackground());
        chooseReaderPanel1.setFlag(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_CardLayout = new javax.swing.JPanel();
        chooseReaderPanel1 = new view.main.librarian.ChooseReaderPanel();
        readerPanel = new view.main.librarian.ReaderPanel();
        profilePanel = new view.profile.ProfilePanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Side = new javax.swing.JPanel();
        jLabel_LogOut = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel_Borrow = new javax.swing.JPanel();
        jLabel_Borrow = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_Return = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_Return = new javax.swing.JLabel();
        jPanel_Reader = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel_Reader = new javax.swing.JLabel();
        jPanel_Profile = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_Profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management Program");

        jPanel_CardLayout.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_CardLayout.setLayout(new java.awt.CardLayout());
        jPanel_CardLayout.add(chooseReaderPanel1, "choose");
        jPanel_CardLayout.add(readerPanel, "reader");
        jPanel_CardLayout.add(profilePanel, "profile");

        getContentPane().add(jPanel_CardLayout, java.awt.BorderLayout.CENTER);

        jPanel_Title.setBackground(new java.awt.Color(0, 153, 153));
        jPanel_Title.setPreferredSize(new java.awt.Dimension(1470, 100));
        jPanel_Title.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel_Title.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Management Program");
        jPanel_Title.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Title, java.awt.BorderLayout.NORTH);

        jPanel_Side.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Side.setPreferredSize(new java.awt.Dimension(150, 700));
        jPanel_Side.setLayout(new java.awt.BorderLayout());

        jLabel_LogOut.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit_20px.png"))); // NOI18N
        jLabel_LogOut.setText("Log out");
        jLabel_LogOut.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel_LogOut.setPreferredSize(new java.awt.Dimension(34, 50));
        jLabel_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LogOutMouseClicked(evt);
            }
        });
        jPanel_Side.add(jLabel_LogOut, java.awt.BorderLayout.SOUTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 440));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jPanel_Borrow.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Borrow.setLayout(new java.awt.BorderLayout());

        jLabel_Borrow.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Borrow.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Borrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Borrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrow.png"))); // NOI18N
        jLabel_Borrow.setText("Borrow");
        jLabel_Borrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Borrow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel_Borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BorrowMouseClicked(evt);
            }
        });
        jPanel_Borrow.add(jLabel_Borrow, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(235, 235, 235));
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 2));
        jPanel_Borrow.add(jSeparator1, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel_Borrow);

        jPanel_Return.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Return.setLayout(new java.awt.BorderLayout());
        jPanel_Return.add(jSeparator2, java.awt.BorderLayout.SOUTH);

        jLabel_Return.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Return.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Return.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        jLabel_Return.setText("Return");
        jLabel_Return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Return.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel_Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ReturnMouseClicked(evt);
            }
        });
        jPanel_Return.add(jLabel_Return, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel_Return);

        jPanel_Reader.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Reader.setLayout(new java.awt.BorderLayout());
        jPanel_Reader.add(jSeparator3, java.awt.BorderLayout.SOUTH);

        jLabel_Reader.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Reader.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Reader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Reader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel_Reader.setText("Reader");
        jLabel_Reader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Reader.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel_Reader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ReaderMouseClicked(evt);
            }
        });
        jPanel_Reader.add(jLabel_Reader, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel_Reader);

        jPanel_Profile.setBackground(new java.awt.Color(0, 204, 204));
        jPanel_Profile.setLayout(new java.awt.BorderLayout());
        jPanel_Profile.add(jSeparator4, java.awt.BorderLayout.SOUTH);

        jLabel_Profile.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Profile.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Profile_50px.png"))); // NOI18N
        jLabel_Profile.setText("Profile");
        jLabel_Profile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_Profile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel_Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ProfileMouseClicked(evt);
            }
        });
        jPanel_Profile.add(jLabel_Profile, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel_Profile);

        jPanel_Side.add(jPanel5, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel_Side, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_BorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BorrowMouseClicked
        // TODO add your handling code here:
        jPanel_Borrow.setBackground(jPanel_Title.getBackground());
        jPanel_Return.setBackground(jPanel_Side.getBackground());
        jPanel_Reader.setBackground(jPanel_Side.getBackground());
        jPanel_Profile.setBackground(jPanel_Side.getBackground());
        UIController.showCardLayout("choose", jPanel_CardLayout);
        chooseReaderPanel1.setFlag(1);
    }//GEN-LAST:event_jLabel_BorrowMouseClicked

    private void jLabel_ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReturnMouseClicked
        // TODO add your handling code here:
        jPanel_Return.setBackground(jPanel_Title.getBackground());
        jPanel_Borrow.setBackground(jPanel_Side.getBackground());
        jPanel_Reader.setBackground(jPanel_Side.getBackground());
        jPanel_Profile.setBackground(jPanel_Side.getBackground());
        UIController.showCardLayout("choose", jPanel_CardLayout);
        chooseReaderPanel1.setFlag(2);
    }//GEN-LAST:event_jLabel_ReturnMouseClicked

    private void jLabel_ReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReaderMouseClicked
        // TODO add your handling code here:
        jPanel_Reader.setBackground(jPanel_Title.getBackground());
        jPanel_Borrow.setBackground(jPanel_Side.getBackground());
        jPanel_Return.setBackground(jPanel_Side.getBackground());
        jPanel_Profile.setBackground(jPanel_Side.getBackground());
        UIController.showCardLayout("reader", jPanel_CardLayout);
    }//GEN-LAST:event_jLabel_ReaderMouseClicked

    private void jLabel_ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ProfileMouseClicked
        // TODO add your handling code here:
        jPanel_Profile.setBackground(jPanel_Title.getBackground());
        jPanel_Borrow.setBackground(jPanel_Side.getBackground());
        jPanel_Return.setBackground(jPanel_Side.getBackground());
        jPanel_Reader.setBackground(jPanel_Side.getBackground());
        UIController.showCardLayout("profile", jPanel_CardLayout);
    }//GEN-LAST:event_jLabel_ProfileMouseClicked

    private void jLabel_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LogOutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jLabel_LogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianMainFrame().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.main.librarian.ChooseReaderPanel chooseReaderPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Borrow;
    private javax.swing.JLabel jLabel_LogOut;
    private javax.swing.JLabel jLabel_Profile;
    private javax.swing.JLabel jLabel_Reader;
    private javax.swing.JLabel jLabel_Return;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Borrow;
    private javax.swing.JPanel jPanel_CardLayout;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JPanel jPanel_Reader;
    private javax.swing.JPanel jPanel_Return;
    private javax.swing.JPanel jPanel_Side;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private view.profile.ProfilePanel profilePanel;
    private view.main.librarian.ReaderPanel readerPanel;
    // End of variables declaration//GEN-END:variables
}
