/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main.librarian;

import control.librarian.BookLoan;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.database.Reader;
import model.database.Rule;
import swing.UIController;
import utilities.File;

/**
 *
 * @author Admin
 */
public class LoanDialog extends javax.swing.JDialog {

    private BookLoan bookLoan;
    private Reader reader;
    private DefaultTableModel modelBookList;
    private DefaultTableModel modelChosenBook;
    private Rule rule;
    /**
     * Creates new form LoanDialog
     * @param parent
     * @param modal
     * @param parentPanel
     */
    public LoanDialog(java.awt.Frame parent, boolean modal, JPanel parentPanel) {
        super(parent, modal);
        initComponents();
        jTextArea_Detail.setWrapStyleWord(true);
        bookLoan = new BookLoan();
        rule = ChooseReaderPanel.rule;
        reader = bookLoan.getReaderInformation(ChooseReaderPanel.username);
        modelBookList = (DefaultTableModel) jTable_BookList.getModel();
        modelChosenBook = (DefaultTableModel) jTable_ChosenBook.getModel();
        bookLoan.loadBookList(modelBookList);
        setReaderInformation();
        setLocationRelativeTo(null);
        setTableView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Gender = new javax.swing.JLabel();
        jLabel_DateOfBirth = new javax.swing.JLabel();
        jLabel_PhoneNumber = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_DayStart = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_Detail = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_SearchBook = new javax.swing.JTextField();
        jButton_ClearSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_BookList = new javax.swing.JTable();
        jButton_Choose = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ChosenBook = new javax.swing.JTable();
        jButton_ClearBook = new javax.swing.JButton();
        jButton_Remove = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_Borrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrow Book");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reader information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 35, 10));

        jLabel_Name.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Name.setText("Name: ");
        jPanel1.add(jLabel_Name);

        jLabel_Gender.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Gender.setText("Gender: ");
        jPanel1.add(jLabel_Gender);

        jLabel_DateOfBirth.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_DateOfBirth.setText("Date of birth: ");
        jPanel1.add(jLabel_DateOfBirth);

        jLabel_PhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_PhoneNumber.setText("Phone number: ");
        jPanel1.add(jLabel_PhoneNumber);

        jLabel_Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Email.setText("Email: ");
        jPanel1.add(jLabel_Email);

        jLabel_DayStart.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_DayStart.setText("Registration date: ");
        jPanel1.add(jLabel_DayStart);

        jLabel_Address.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel_Address.setText("Address: ");
        jPanel1.add(jLabel_Address);

        jScrollPane4.setBorder(null);

        jTextArea_Detail.setEditable(false);
        jTextArea_Detail.setColumns(20);
        jTextArea_Detail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextArea_Detail.setLineWrap(true);
        jTextArea_Detail.setRows(5);
        jScrollPane4.setViewportView(jTextArea_Detail);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search for books", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Book name");

        jTextField_SearchBook.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_SearchBook.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_SearchBookCaretUpdate(evt);
            }
        });

        jButton_ClearSearch.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_ClearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        jButton_ClearSearch.setText("Clear");
        jButton_ClearSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ClearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextField_SearchBook)
                .addGap(18, 18, 18)
                .addComponent(jButton_ClearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_SearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ClearSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_BookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Location", "Author", "Publisher", "Category", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_BookList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable_BookList);

        jButton_Choose.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Choose.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Choose.setText("Choose");
        jButton_Choose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChooseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Book list");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Chosen book");
        jLabel12.setToolTipText("");

        jTable_ChosenBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Author"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ChosenBook.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable_ChosenBook);

        jButton_ClearBook.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_ClearBook.setForeground(new java.awt.Color(51, 51, 51));
        jButton_ClearBook.setText("Clear");
        jButton_ClearBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ClearBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearBookActionPerformed(evt);
            }
        });

        jButton_Remove.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Remove.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Remove.setText("Remove");
        jButton_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Exit.setText("Exit");
        jButton_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_Borrow.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton_Borrow.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Borrow.setText("Borrow");
        jButton_Borrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(293, 293, 293)
                        .addComponent(jButton_Choose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_Borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton_ClearBook, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton_Remove))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Remove)
                    .addComponent(jButton_ClearBook)
                    .addComponent(jButton_Choose)
                    .addComponent(jButton_Exit)
                    .addComponent(jButton_Borrow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setReaderInformation() {
        jLabel_Name.setText("Name: " + reader.getName());
        jLabel_Gender.setText("Gender: " + reader.getGender());
        jLabel_DateOfBirth.setText("Date of birth: " + reader.getDateOfBirth());
        jLabel_PhoneNumber.setText("Phone: " + reader.getPhone());
        jLabel_Email.setText("Email: " + reader.getEmail());
        jLabel_DayStart.setText("Registration date: " + reader.getRegisteredDate());
        jTextArea_Detail.setText(reader.getAddress());
    }
    
    private void setTableView() {
        UIController.setDefaultTableHeader(jTable_BookList);
        UIController.setDefaultTableHeader(jTable_ChosenBook);
    }

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jTextField_SearchBookCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_SearchBookCaretUpdate
        // TODO add your handling code here:
        String tuKhoa = jTextField_SearchBook.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(modelBookList);
        jTable_BookList.setRowSorter(trs);

        trs.setRowFilter(RowFilter.regexFilter("(?i)" + tuKhoa, 1));
    }//GEN-LAST:event_jTextField_SearchBookCaretUpdate

    private void jButton_ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChooseActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_BookList.convertRowIndexToModel(jTable_BookList.getSelectedRow());
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách muốn mượn!");
            return;
        }
        if(modelChosenBook.getRowCount() == ChooseReaderPanel.remainingBook) {
            JOptionPane.showMessageDialog(this, "Đã đạt số sách tối đa được mượn!");
            return;
        }
        if(Integer.parseInt(modelBookList.getValueAt(selectedRow, 6).toString()) == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sách này đã hết, không thể mượn. Vui lòng chọn sách khác!");
            return;
        }
        
        if(bookLoan.findChosenBook(modelChosenBook, modelBookList.getValueAt(selectedRow, 0).toString())) {
            JOptionPane.showMessageDialog(this, "Sách này đã được chọn!");
            return;
        }
        
        if(bookLoan.findBorrowedBook(ChooseReaderPanel.username, modelBookList.getValueAt(selectedRow, 0).toString())) {
            JOptionPane.showMessageDialog(this, "Không thể mượn sách mà độc giả đang mượn. Vui lòng chọn sách khác!");
            return;
        }
        
        Vector vt = new Vector();
        vt.add(modelBookList.getValueAt(selectedRow, 0));
        vt.add(modelBookList.getValueAt(selectedRow, 1));
        vt.add(modelBookList.getValueAt(selectedRow, 3));
        modelChosenBook.addRow(vt);
    }//GEN-LAST:event_jButton_ChooseActionPerformed

    private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_ChosenBook.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách muốn xóa!");
            return;
        }
        modelChosenBook.removeRow(selectedRow);
    }//GEN-LAST:event_jButton_RemoveActionPerformed

    private void jButton_ClearBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearBookActionPerformed
        // TODO add your handling code here:
        modelChosenBook.setNumRows(0);
    }//GEN-LAST:event_jButton_ClearBookActionPerformed

    private String getReaderInformation() {
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        
        Calendar c = Calendar.getInstance();
        Date startDate = new Date();
        c.setTime(startDate);
        c.add(Calendar.DATE, rule.getSoNgayMuonToiDa());
        
        String strStartDate = dateFormatter.format(startDate);
        String strEndDate = dateFormatter.format(c.getTime());
        
        return jLabel_Name.getText() + "\n" +
        jLabel_Gender.getText() + "\n" +
        jLabel_DateOfBirth.getText() + "\n" +
        jLabel_PhoneNumber.getText() + "\n" +
        jLabel_Email.getText() + "\n" +
        jLabel_DayStart.getText() + "\n" +
        "Address: " + jTextArea_Detail.getText() + "\n" +
        "Borrow date: " + strStartDate + "\n" +
        "Expiration date: " + strEndDate + "\n";
    }
    
    private void jButton_BorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BorrowActionPerformed
        // TODO add your handling code here:
        if(modelChosenBook.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa có sách được chọn!");
            return;
        }
        bookLoan.borrowBook(ChooseReaderPanel.username, modelChosenBook);
        JOptionPane.showMessageDialog(this, "Mượn sách thành công!");
        
        int loanID = bookLoan.getCurrentBorrow();
        File.xuatFilePDF("PhieuMuon" + loanID, "PHIẾU MƯỢN SÁCH " + loanID, getReaderInformation(), modelChosenBook);
        this.dispose();
    }//GEN-LAST:event_jButton_BorrowActionPerformed

    private void jButton_ClearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearSearchActionPerformed
        // TODO add your handling code here:
        jTextField_SearchBook.setText("");
    }//GEN-LAST:event_jButton_ClearSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Borrow;
    private javax.swing.JButton jButton_Choose;
    private javax.swing.JButton jButton_ClearBook;
    private javax.swing.JButton jButton_ClearSearch;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Remove;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_DateOfBirth;
    private javax.swing.JLabel jLabel_DayStart;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Gender;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_PhoneNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_BookList;
    private javax.swing.JTable jTable_ChosenBook;
    private javax.swing.JTextArea jTextArea_Detail;
    private javax.swing.JTextField jTextField_SearchBook;
    // End of variables declaration//GEN-END:variables
}
